### ISSUE TITLE
lib  pillow

### ISSUE THREAD

**Issue by Xinelin** [juddisjudd/D4-Autoskill#1]
pillow is necessary indeed
add:pip install pillow
pls

**Comment by juddisjudd** [comment]
> pillow is necessary indeed add:pip install pillow pls

This does not use pillow, uses opencv.

**Comment by Xinelin** [comment]
I copyed `pip install opencv-python numpy pyautogui pyscreenshot colorama` debug return 
![image](https://github.com/juddisjudd/D4-Autoskill/assets/43874766/309792e8-035d-461a-97c9-a0deba27e955)
and then i did install pillow ,Autoskill worked.

**Comment by juddisjudd** [comment]
> I copyed `pip install opencv-python numpy pyautogui pyscreenshot colorama` Autoskill didn`t run and debug return : ![image](https://user-images.githubusercontent.com/43874766/238517248-309792e8-035d-461a-97c9-a0deba27e955.png) But when i did install pillow ,Autoskill worked.

My apologies I forgot I reworked this. I will push an update June 1st.
