### ISSUE TITLE
Ban

### ISSUE THREAD

**Issue by dex6789** [juddisjudd/D4-Autoskill#3]
Hello,  is there a way that warden bans you for using this as it is an automaton ?
Thx for your work by the way

**Comment by Naladdar** [comment]
The Script does not interact with D4, it scans the window for a picture, if found it presses a button.

**Comment by juddisjudd** [comment]
I cannot see this causing bans since it doesn't really do much and like Naladdar said above, it just scans the screen for a match of your local image and presses a button.
